export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const SERVER_ERROR = "SERVER_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";

export const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";
export const CHANGE_TASK_SUCCESS = "CHANGE_TASK_SUCCESS";

export const SET_TASK_TIME = "SET_TASK_TIME";

export const FETCH_ACTIVE_TASK = "FETCH_ACTIVE_TASK";
export const FETCH_ACTIVE_TASK_SUCCESS = "FETCH_ACTIVE_TASK_SUCCESS";

export const ADD_TASK_COMMENT = "ADD_TASK_COMMENT";

export const FETCH_ALL_TASKS = 'FETCH_ALL_TASKS';
export const FETCH_ALL_TASKS_SUCCESS = 'FETCH_ALL_TASKS_SUCCESS';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';