export const FETCH_LOGGED_USER = "FETCH_LOGGED_USER";
export const FETCH_LOGGED_USER_SUCCESS = "FETCH_LOGGED_USER_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGOUT = "LOGOUT";

export const CHANGE_USER_STATUS = "CHANGE_USER_STATUS";

export const SERVER_ERROR = "SERVER_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const FETCH_USER_TASKS = "FETCH_USER_TASKS";
export const FETCH_USER_TASKS_SUCCESS = "FETCH_USER_TASKS_SUCCESS";

export const SET_TASK_TIME = "SET_TASK_TIME";

export const FETCH_TASK_BY_ID = "FETCH_TASK_BY_ID";
export const FETCH_TASK_BY_ID_SUCCESS = "FETCH_TASK_BY_ID_SUCCESS";

export const FETCH_ACTIVE_TASK = "FETCH_ACTIVE_TASK";
export const FETCH_ACTIVE_TASK_SUCCESS = "FETCH_ACTIVE_TASK_SUCCESS";
export const RESET_ACTIVE_TASK = "RESET_ACTIVE_TASK";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";

export const CHANGE_TASK = "CHANGE_TASK";
export const CHANGE_TASK_SUCCESS = "CHANGE_TASK_SUCCESS";

export const REMOVE_TASK = "REMOVE_TASK";
export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";

export const FETCH_ALL_TASKS = "FETCH_ALL_TASKS";
export const FETCH_ALL_TASKS_SUCCESS = "FETCH_ALL_TASKS_SUCCESS";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const FETCH_CHAT_ROOM = "FETCH_CHAT_ROOM";
export const FETCH_CHAT_ROOM_SUCCESS = "FETCH_CHAT_ROOM_SUCCESS";

export const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";
export const SEND_TASK_MESSAGE = "SEND_TASK_MESSAGE";

export const ATTEND_CHAT = "ATTEND_CHAT";
export const ATTEND_CHAT_SUCCESS = "ATTEND_CHAT_SUCCESS";

export const LEAVE_CHAT = "LEAVE_CHAT";
export const LEAVE_CHAT_SUCCESS = "LEAVE_CHAT_SUCCESS";

export const SET_SOCKET_CONNECTION = "SET_SOCKET_CONNECTION";
export const SET_SOCKET_CONNECTION_SUCCESS = "SET_SOCKET_CONNECTION_SUCCESS";

export const FETCH_MESSAGES_LIST_SUCCESS = "FETCH_MESSAGES_LIST_SUCCESS";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";

export const GET_ACTIVE_MESSAGE = "GET_ACTIVE_MESSAGE";
export const RESET_ACTIVE_MESSAGE = "RESET_ACTIVE_MESSAGE";

export const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";

export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const REMOVE_MESSAGE_SUCCESS = "REMOVE_MESSAGE_SUCCESS";
